### ISSUE TITLE
Previous Version Bug/Glitch?

### ISSUE THREAD

**Issue by BuMmR88** [jhowkNx/Heist-Control-v2#1]
I was running your previous version of heist control... the 2.0. I did 3 people insta play. Set the money for 20 / 40 / 40 and ran the game. The guards act weird. The first time I shot them and they came back to life. The second time the person with me told me to kill myself so we could restart. It said I had 1 team life left. I tried every way to kill myself in game but even though I was dying, it still said 1 team life left... What the heck? Is this fixed in the new version? Am I doing something wrong? I also turned off ALL my protections b4 we started doing the heist to be on the safe side.

**Comment by jhowkNx** [comment]
Hello.
As said before, HC can't interfere directly with the enemies in your Heist.
The negative effects that affect your enemies are the powers of cutting powder, which only affects the aim of your enemies.
I believe this can be caused by lag, desync between players in your lobby and this has happened to me and still happens when there is some player with high desync during the match.
