### ISSUE TITLE
Long ending cayo perico heist

### ISSUE THREAD

**Issue by igobythisname** [jhowkNx/Heist-Control-v2#17]
before the Contract DLC, i would run the cayo perico heist using automated presets>quick preset, and I would get a very short cutscene at the end of the heist, just dropping off the bags and getting paid. now, ever since the update+2T1 menu update+heist control updates, i get a long cutscene after the heist. is there a way to disable this? i would rather keep having the shorter cutscene. thank in advance!

**Comment by jhowkNx** [comment]
Hello,
As you explained before, you are always using the option to reset the Heist, what happens is that this option always resets also the number of times you did the heist, so this cutscene is only shown for the first time you do the heist, understand?
So when using this option, you will always see the first long scene, because the preset no longer changes the number of heists that have currently been done.

Honestly, the Heist reset options are only valid for people who can't get started at all.
You can use another preset to overwrite the current one or even start another one
