### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Robberrug** [jhowkNx/Heist-Control-v2#4]
I did the diamond casino heist but I gave 85% cut to my friend and 15% to me and I didn’t get the money and I’m afraid that my friend didn’t get the money as well how do i make it so that my friend and me got the money, I didn’t edit anything I just got the script and it’s diamond if that helps

**Comment by jhowkNx** [comment]
Hello.
It sounds like your problem must be due to cooldown.
There is a limit that is imposed by the server (server-side), you can only earn high cash values every 15 minutes (payments), so I advise you to wait those 15 minutes to start the same heist again, or if you prefer, you can play other heists, maybe ACT 2 Doomsday?

**Comment by Robberrug** [comment]
So perico?

**Comment by Robberrug** [comment]
After casino

**Comment by jhowkNx** [comment]
Yes, you choose. After you finish Cayo Perico Heist, you can play the Casino Heist again and so on.

**Comment by jhowkNx** [comment]
I am closing this case because it is not about the script itself, regarding the payment it is necessary to wait for the cooldown, this is already described in the script, however, if you find any problem that affects the use of the Script, report it so we can solve it.
