### ISSUE TITLE
Bug in Diamond Casino Heist Auto Preset

### ISSUE THREAD

**Issue by buxy97** [jhowkNx/Heist-Control-v2#47]
There is a bug in the automatic preset of the diamond casino heist task. After I start this script, the bonus ratio of my teammates will all become 146%. After completing the heist, I will get 3.5mil, but my teammates' income will exceed the task bonus limit, resulting in no income.

**Comment by jhowkNx** [comment]
That value you see after completing the heist.... which is between 7 and 8 million for your friends, is a visual bug. On your friends' screens, they will see the normal value, which is 3.5M.
Don't forget to select the low level buyer, this is important to ensure that payment is made to everyone.

**Comment by buxy97** [comment]
Today I tried again, after completing the heist I received 3.5mil, but my teammate received nothing. It's not a visual bug, but a real bug.

**Comment by jhowkNx** [comment]
Which preset are you having problems with?
Target: Diamond/Gold?
Method: BigCon/Aggressive/Silent?

**Comment by buxy97** [comment]
Which preset are you having problems with?
Target:  **Diamond**
Method:  **BigCon, but silent method may also has this problem.**

**Comment by jhowkNx** [comment]
I checked and noticed that all my heist members were paid perfectly when using the preset you mentioned. I didn't notice any issues regarding payouts.
If you're using instant finish for BigCon or Silent Sneaky it won't work well and might mess up the payout.

If you are using a version later than 2.27.0 you will receive an in-game notification to update, if not use the latest version:
[Heist Control v2.29.0](https://github.com/jhowkNx/Heist-Control-v2/files/9282952/Heist.Control.v2.29.0.zip)

Any doubt let me know!

**Comment by buxy97** [comment]
After 2.29.2 update,  my teammates received 300k while I received 3.5mil when we finished casino heist  : )
I want to show you the screenshot but Idk how to do it in github

**Comment by jhowkNx** [comment]
The presets have not been changed, the payoffs are still the same. As I said before I have confirmed myself that the payouts are being paid correctly playing with randoms/friends, there are no problems with that.
If there were any problems, then there would be a quick update to fix it and at the moment I can assure you that there is nothing wrong with the presets.
100% sure that your friends are at the cooldown limit and are getting the extra 300k for it. Even if they play their heist legitimately and then play yours, they will not get the full payout because of it.
